name: Trivy Container Scan 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t dvwa-image .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@main
        with:
          image-ref: dvwa-image
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL